Od/start tx validate declare execution context
keep-starknet-strange/snos pull request #172
Opened 2024-04-16 16:45 UTC by odesenfans

Issue Number: N/A

## Type

- [x] feature
- [ ] bugfix
- [ ] dev (no functional changes, no API changes)
- [ ] fmt (formatting, renaming)
- [ ] build
- [ ] docs
- [ ] testing

## Description

## Breaking changes?

- [ ] yes
- [x] no

2024-04-16 21:17 UTC, notlesh requested changes
Other `start_tx` hints are in `execution.rs`.

Looks good otherwise.

2024-04-16 21:21 UTC, maciejka reviewed
Not on critical path.

2024-04-17 09:34 UTC, odesenfans commented
> Other `start_tx` hints are in `execution.rs`.
> 
> Looks good otherwise.

Maciej and I discussed that hints should be in files named like their Python counterparts. We'll do a cleanup pass for the other hints once we're done.

2024-04-17 16:31 UTC, notlesh approved these changes

2024-04-18 09:38 UTC, merged