Ft/handle all tx traces
keep-starknet-strange/snos pull request #330
Opened 2024-08-29 13:34 UTC by ftheirs

Problem: at the moment only Invoke transactions were supported

Solution: process traces and add type conversion for reverted Invoke transaction, DeployAccount, Declare and L1Handler

Issue Number: N/A

## Type

- [x] feature
- [ ] bugfix
- [ ] dev (no functional changes, no API changes)
- [ ] fmt (formatting, renaming)
- [ ] build
- [ ] docs
- [ ] testing

## Description

## Breaking changes?

- [ ] yes
- [x] no

2024-08-29 20:34 UTC, HermanObst requested changes
@ftheirs please modularize all the different tx with each version.
see 
[starknet_rs_tx_to_internal_tx](https://github.com/keep-starknet-strange/snos/blob/main/crates/bin/prove_block/src/types.rs#L186-L205)

2024-08-30 09:58 UTC, odesenfans requested changes

2024-08-30 09:58 UTC, odesenfans commented on crates/rpc-replay/src/transactions.rs
>  ) -> Result<blockifier::transaction::transaction_execution::Transaction, Box<dyn Error>> {
For another PR, but we really need to return something better than `Box<dyn Error>` here.

2024-08-30 09:58 UTC, odesenfans commented on crates/rpc-replay/src/transactions.rs
> +            let starknet_contract_class = provider.get_class(BlockId::Number(block_number), class_hash).await?;
Could you put the `ClassInfo` generation in a new function?

2024-08-30 09:58 UTC, odesenfans commented on crates/rpc-replay/src/transactions.rs
> +            let contract_class = generic_sierra_cc.compile()?.get_blockifier_contract_class()?.clone();
There's (or at least should be) a `to_blockifier_contract_class` method that hides the clone.

2024-08-30 09:58 UTC, odesenfans commented on crates/rpc-replay/src/transactions.rs
> +            let generic_sierra_cc = match starknet_contract_class {
To deal with the legacy/deprecated/Cairo0 (these are synonyms) contracts, you simply need to move the compilation code + conversion to Blockifier `ContractClass` here and do the appropriate thing for Cairo0 in the other arm of the match. Please resolve it in this PR.

2024-08-30 09:58 UTC, odesenfans commented on crates/rpc-replay/src/transactions.rs
> +        Transaction::L1Handler(tx) => {
As @HermanObst already suggested, please split every arm of this match into separate functions.

2024-08-30 09:58 UTC, odesenfans commented on crates/rpc-replay/src/transactions.rs
> +            let fee = Fee(0);
Looking at the explorer, this seems to be correct. Replace the TODO by a comment saying that fees are 0 for L1 handler txs.

2024-08-30 17:55 UTC, HermanObst requested changes
@ftheirs good job man! 
one last comment: remove all the `unwrap()` that you are using in favor to correctly handle the errors.

In general, we never accept unwrap() as they can make the program panic, basically bypassing Rust safety.
We only accept if there is a comment, clearly explaining why a given unwrap() will never fail. But handling the error is better practice. 

 Sorry that I didnt catch it before

2024-09-03 23:08 UTC, ftheirs commented
Closing this since it will be split in several PRs

2024-09-03 23:08 UTC, closed without merging