Test: add pie validity check to prove block
keep-starknet-strange/snos pull request #383
Opened 2024-09-24 18:53 UTC by HermanObst

Problem: We weren't performing validation checks on the PIEs we were generating.
Fix: Adds run_validity_checks() in our prove block tests

2024-09-24 19:37 UTC, ftheirs approved these changes
LGTM

2024-09-24 20:08 UTC, notlesh requested changes
We should add this to `execute_txs_and_run_os()` so that it will be checked in our integration tests as well

2024-09-24 20:09 UTC, notlesh commented on crates/bin/prove_block/tests/prove_block.rs
> +    assert!(pie.run_validity_checks().is_ok());
Not a big deal, but an `expect()` with a clear message would be better

2024-09-25 15:58 UTC, notlesh approved these changes

2024-09-25 18:02 UTC, merged