Fix reexecute with blockifier
keep-starknet-strange/snos pull request #436
Opened 2024-11-20 19:16 UTC by ftheirs

WIP

Closes https://github.com/keep-starknet-strange/snos/issues/434
Issue Number: N/A

## Type

- [ ] feature
- [x] bugfix
- [ ] dev (no functional changes, no API changes)
- [ ] fmt (formatting, renaming)
- [ ] build
- [ ] docs
- [ ] testing

## Description

## Breaking changes?

- [ ] yes
- [x] no

2024-11-20 19:22 UTC, HermanObst requested changes
Minor change. The rest looks great

2024-11-20 19:22 UTC, HermanObst commented on crates/bin/prove_block/src/reexecute.rs
> +    previous_block_hash: Felt252,
Dont call this `previous_block_hash`. 
Is misleading as we are calling previous to current - 1 block

`old_block_hash` its ok. But  `buffer_block_hash` would be ideal

2024-11-20 20:25 UTC, HermanObst approved these changes
NICE, LGTM!!!!!!!

2024-11-21 11:43 UTC, whichqua approved these changes
LGTM!
Good work @ftheirs

2024-11-21 11:55 UTC, GMKrieger approved these changes
Great work, Fer!

2024-11-21 12:18 UTC, merged