Dict hints
keep-starknet-strange/snos pull request #455
Opened 2024-12-27 15:07 UTC by ftheirs

Implement dictionary hints related to compression process.
Add constants.rs file to define constants that are needed across several hints

Issue Number: N/A

## Type

- [x] feature
- [ ] bugfix
- [ ] dev (no functional changes, no API changes)
- [ ] fmt (formatting, renaming)
- [ ] build
- [ ] docs
- [ ] testing

## Description

## Breaking changes?

- [ ] yes
- [x] no

2025-01-02 15:43 UTC, whichqua commented on crates/starknet-os/src/hints/dict.rs
> +    let prev_offset = dict_tracker.get(&bucket_index).unwrap().clone();
Handling this unwrap is the only thing I can thing of.

2025-01-02 15:44 UTC, whichqua approved these changes
Should be good!

2025-01-06 18:05 UTC, notlesh requested changes
The code looks good to me, but I would suggest one thing:

In `cairo-lang` this all comes from a file called `compression.cairo`, and we have tried to keep our file structure similar to theirs. So, my suggestions:

* Rename `dict.rs` -> `compression.rs`
* Drop `constants.rs` and include its contents in `compression.rs`

2025-01-06 22:34 UTC, notlesh approved these changes

2025-01-07 13:00 UTC, merged