Add support to Pathfinder v0_8
keep-starknet-strange/snos pull request #456
Opened 2024-12-30 13:29 UTC by GMKrieger

Issue Number: N/A

## Type

- [x] feature
- [ ] bugfix
- [ ] dev (no functional changes, no API changes)
- [ ] fmt (formatting, renaming)
- [ ] build
- [ ] docs
- [ ] testing

## Description

Adds support for pathfinder v0_8. It coalesces the 2 types of request on the client and then converts the new version to the one supported by snos.

## Breaking changes?

- [ ] yes
- [x] no

2025-01-02 08:20 UTC, whichqua requested changes
Left some thoughts, let me know what you think.

2025-01-02 08:20 UTC, whichqua commented on crates/rpc-client/src/client.rs
> +    Rpcv07(String),
Why do we need the `String` here? The enum should handle it

2025-01-02 08:20 UTC, whichqua commented on crates/rpc-client/src/client.rs
> +        let rpc_version = match &version {
Instead of doing this, implement `Display` for `ClientVersion`

2025-01-02 08:20 UTC, whichqua commented on crates/rpc-client/src/client.rs
> +impl TryFrom<&str> for ClientVersion {
Consider replacing with `impl FromStr` because it allows more flexibility dealing with different string types.

2025-01-02 08:20 UTC, whichqua commented on crates/bin/prove_block/tests/prove_block.rs
> +#[case::small_block_with_only_invoke_txs(76793, "v0_7")]
Does this mean these tests cannot be run on `v0.8`?

2025-01-02 08:20 UTC, whichqua commented on crates/rpc-client/src/pathfinder/proofs.rs
> +    for node in &storage_proof.classes_proof {
Consider a more declarative approach
```suggestion
        let class_proof = storage_proof
        .classes_proof
        .iter()
        .map(convert_to_trie_node)
        .collect();
```

2025-01-02 08:20 UTC, whichqua commented on crates/rpc-client/src/pathfinder/proofs.rs
> +    let mut contract_proof: Vec<TrieNode> = Vec::new();
Consider a more declarative approach
```suggestion
   let contract_proof: Vec<TrieNode> = storage_proof.contracts_proof.nodes
    .iter()
    .map(|node| convert_to_trie_node(node))
    .collect();

let storage_proofs: Vec<Vec<TrieNode>> = storage_proof.contracts_storage_proofs
    .iter()
    .map(|nodes| {
        nodes
            .iter()
            .map(|node| convert_to_trie_node(node))
            .collect()
    })
    .collect();

```

2025-01-02 08:20 UTC, whichqua commented on crates/rpc-client/src/pathfinder/proofs.rs
> +    let contract_data: Option<ContractData>;
This should help you avoid the `if`:
```rs
let contract_data = storage_proof
    .contracts_storage_proofs
    // Get the first "proof" only if it exists
    .get(0)
    // Filter out if the first proof is empty
    .filter(|proof_nodes| !proof_nodes.is_empty())
    .map(|proof_nodes| {
        let first_node = &proof_nodes[0];
        let root = first_node.node_hash;

        match &first_node.node {
            MerkleNode::Binary { left, .. } if left.to_hex_string() == "0x0" => {
                // If left is "0x0", then storage_proofs is empty
                ContractData {
                    root,
                    storage_proofs: vec![],
                }
            }
            // For all other cases (including `MerkleNode::Edge`),
            // store the computed `storage_proofs`.
            _ => ContractData { root, storage_proofs },
        }
    });
```

2025-01-02 08:23 UTC, whichqua commented on crates/rpc-client/src/client.rs
> +    Rpcv07(String),
This is related to https://github.com/keep-starknet-strange/snos/pull/456#discussion_r1900622544

2025-01-07 17:04 UTC, glihm reviewed
@GMKrieger for this PR we may also take in account that we only have one proof now for all the keys, instead of individual proofs, which should change the verification function according to that to accept the union path returned by the RPC call.

2025-01-08 19:14 UTC, GMKrieger commented on crates/bin/prove_block/tests/prove_block.rs
> +#[case::small_block_with_only_invoke_txs(76793, "v0_7")]
They should be able to run on v0_8, but they were not made for that, therefore I left them using the old version to maintain their original purpose and added new tests (that repeat some of the old tests that had errors when first developing) on the new api.

2025-01-08 20:39 UTC, ftheirs requested changes

2025-01-08 20:39 UTC, ftheirs commented on crates/bin/prove_block/tests/prove_block.rs
> +#[case::small_block_with_only_invoke_txs(76793, "v0_7")]
I think that it would be good to have a default variable that is set to "v0_7" and maybe put all the "v0_8" tests in a different file / different test. So, once the v0.8 is working for all the tests, we can just replace the default. Besides, it's a little bit cleaner

2025-04-03 18:25 UTC, notlesh commented on crates/rpc-client/src/pathfinder/proofs.rs
> +pub fn convert_storage_to_pathfinder_proof(storage_proof: StorageProof) -> PathfinderProof {
I think this is the wrong idea. The v0.8 API is an improvement over the Pathfinder one, and is more generic, so I think we want to deprecate all of the pathfinder-specific stuff.

2025-04-03 18:27 UTC, notlesh commented
Closing this for now. We probably want parts of it but I think we will want to go in the direction of removing all the Pathfinder specific code.

There are also some things we've learned since doing this, namely that proofs are mixed together and are not presented in order like they were in Pathfinder.

2025-04-03 18:27 UTC, closed without merging