List hints again
keep-starknet-strange/snos pull request #52
Opened 2023-12-12 18:54 UTC by maciejka

Choose which hints subset you are interested in:
```
cargo run --bin hints all | implemented | unimplemented
```

2023-12-14 10:49 UTC, LucasLvy commented
you need to consider the base hints that are already implemented in the vm (you can use the starknet whitelisted hints file to get those)

2023-12-14 12:49 UTC, LucasLvy commented
and i'd display the number of hints not the actual code

2023-12-14 14:30 UTC, maciejka commented
> and i'd display the number of hints not the actual code

You can use `jq` to process it the way you want:
```
cargo run --bin hints unimplemented | jq length
```

2024-01-02 21:10 UTC, drspacemn commented
Having trouble understanding the purpose of this? This is to display the meta-data for the current hint implementations in SNOS? 

Or simply to output their python strings in a large array?

Since this is meant to be used as a library I'm hesitant to add a top level `bin/` dir that doesn't add to the function of snos

2024-01-02 21:12 UTC, drspacemn reviewed
Having trouble understanding the purpose of this? This is to display the meta-data for the current hint implementations in SNOS?

Or simply to output their python strings in a large array?

Since this is meant to be used as a library I'm hesitant to add a top level bin/ dir that doesn't add to the function of snos

For hint accounting or metadata on dev progress I'd probably like to keep that to `scripts || tests || benches`

2024-01-02 21:33 UTC, maciejka commented
It is a utility like a script. Ultimately it can be used in ci script to detect unimplemented or no longer needed hints.
The scripts dir seems most natural to me. Ok?

2024-01-02 21:42 UTC, drspacemn commented
> The scripts dir seems most natural to me. Ok?

yes that sounds perfect to me

2024-01-02 21:45 UTC, drspacemn commented on src/hints/mod.rs
> +pub fn sn_hint_processor() -> BuiltinHintProcessor {
#54

Will re-init how we set this handler up, so maybe we should hold off on this portion until that is merged

2024-01-08 17:15 UTC, drspacemn approved these changes

2024-01-08 17:15 UTC, drspacemn commented on src/hints/mod.rs
> +    hints: HashMap<&'a str, HintImpl>,
Let's use `String` and get rid of the lifetime

2024-01-08 17:51 UTC, drspacemn requested changes
Let's use `String` to get rid of the lifetime

2024-01-11 21:41 UTC, drspacemn approved these changes

2024-01-11 21:42 UTC, merged